version: '3.9'
services:
  database:
    image: postgres
    restart: always
    environment:
      DB_HOST: database
      POSTGRES_USER: index_development
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: index_development
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  
  redis:
    image: redis
    ports:
      - '6379:6379'
    volumes:
      - redis_data:/data

  app: 
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - database
      - redis
    ports: 
      - '3000:3000'
    stdin_open: true
    tty: true
    volumes:
      - .:/app
    environment:
      RAILS_ENV: development
      DB_HOST: database
      POSTGRES_USER: index_development
      POSTGRES_PASSWORD: letmein
      POSTGRES_DB: index_development

volumes:
  redis_data:
  postgres_data:
