default: &default
  adapter: postgresql
  encoding: unicode
  database: "rails_development"
  username: "index_development"
  password: "CiYQ0gzWnPNgihjwj4t"
  port: '5432'
  host: "database"
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default 