default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("DATABASE_POOL_SIZE") { ENV.fetch("RAILS_MAX_THREADS", 5).to_i } %>
  connect_timeout: 2
  checkout_timeout: 2
  variables:
      statement_timeout: <%= ENV.fetch("STATEMENT_TIMEOUT", 2500).to_i %>

development:
  <<: *default
  database: <%= ENV.fetch("DATABASE_NAME", "index_development") %>
  username: "index_development"
  password: "CiYQ0gzWnPNgihjwj4t"

 