default: &default
  adapter: postgresql
  encoding: unicode
  database: index_development
  username: index_development
  password: letmein
  host: database
  pool: 5
  timeout: 5000

development:
  <<: *default 